### ISSUE TITLE
Quest module showing !s all over the place in new release

### ISSUE THREAD

**Issue by Ghosthree3** [mikepauer/Carbonite#254]
Even when it shouldn't, it used to only show them when you had Show->Custom Icons ticked, but I unticked that because it was really buggy. Now it shows the !s no matter what and it's showing ones it really shouldn't, like quests I've finished.

**Comment by Rythal** [comment]
Are you sure it's wholly doing it, as I fixed quest display in carbonite which would also be drawing !'s all over the place. It could be there is a bug in checking if a quest is complete or not before drawing it.

**Comment by Ghosthree3** [comment]
Ok that's my fault, I just assumed it was Wholly since it was a similar problem. Problem persists even after I disable it.

**Comment by IrcDirk** [comment]
Recheck in latest git version.
