### ISSUE TITLE
Silver Hand Orders

### ISSUE THREAD

**Issue by Palonblade** [mikepauer/Carbonite#573]
When you get your class hall to the point where you can create Silver Hand Orders to complete world quests from the world map when you attempt to do so from the main map this error occurs: Had to unload Carb to actually complete the world quest. 

Date: 2016-11-03 02:24:35
ID: -1
Error occured in: AddOn: Carbonite
Count: 1
Message: Error: AddOn Carbonite attempted to call a forbidden function (UseWorldMapActionButtonSpellOnQuest()) from a tainted execution path.
Debug:
   [C]: UseWorldMapActionButtonSpellOnQuest()
   ..\FrameXML\WorldMapFrame.lua:1912:
      ..\FrameXML\WorldMapFrame.lua:1908
   [C]: ?
   [C]: ?
   [C]: ?
Locals:
None
AddOns:
  GarbageProtector, v
  InspectFix, v4.5.2
  Swatter, v7.1.5675 (TasmanianThylacine)
  Config, v
  NPCScanOverlay, v7.1.0.1
  AckisRecipeList, v7.0.3.8
  AdvancedInterfaceOptions, v1.0.6
  Altoholic, vr172
  AskMrRobot, v46
  Atlas, v1.35.03
  AtlasBattlegrounds, v1.35.00
  AtlasBurningCrusade, v1.35.00
  AtlasCataclysm, v1.35.00
  AtlasClassicWoW, v1.35.00
  AtlasClassOrderHalls, v1.35.00
  AtlasDungeonLocs, v1.35.00
  AtlasLegion, v1.35.04
  AtlasMistsofPandaria, v1.35.00
  AtlasOutdoorRaids, v1.35.00
  AtlasScenarios, v1.35.00
  AtlasTransportation, v1.35.00
  AtlasWarlordsofDraenor, v1.35.00
  AtlasWorldEvents, v3.17
  AtlasWrathoftheLichKing, v1.35.00
  AtlasLoot, vv8.01.06
  AtlasQuest, v4.10.20
  AucAdvanced, v7.1.5675 (TasmanianThylacine)
  AucFilterBasic, v7.1.5675 (TasmanianThylacine)
  AucFilterOutlier, v7.1.5675.5459(7.1/embedded)
  AucMatchUndercut, v7.1.5675.5585(7.1/embedded)
  AucStatHistogram, v7.1.5675 (TasmanianThylacine)
  AucStatiLevel, v7.1.5675 (TasmanianThylacine)
  AucStatPurchased, v7.1.5675 (TasmanianThylacine)
  AucStatSales, v7.1.5675.5598(7.1/embedded)
  AucStatSimple, v7.1.5675 (TasmanianThylacine)
  AucStatStdDev, v7.1.5675 (TasmanianThylacine)
  AucStatWOWEcon, v7.1.5675.5613(7.1/embedded)
  AucUtilAHWindowControl, v7.1.5675.5575(7.1/embedded)
  AucUtilAppraiser, v7.1.5675.5666(7.1/embedded)
  AucUtilAskPrice, v7.1.5675.5599(7.1/embedded)
  AucUtilAutoMagic, v7.1.5675.5587(7.1/embedded)
  AucUtilCompactUI, v7.1.5675.5629(7.1/embedded)
  AucUtilEasyBuyout, v7.1.5675.5576(7.1/embedded)
  AucUtilFixAH, v7.1.5675 (TasmanianThylacine)
  AucUtilItemSuggest, v7.1.5675.5651(7.1/embedded)
  AucUtilPriceLevel, v7.1.5675.5633(7.1/embedded)
  AucUtilScanButton, v7.1.5675.5631(7.1/embedded)
  AucUtilScanFinish, v7.1.5675.5588(7.1/embedded)
  AucUtilScanProgress, v7.1.5675.4979(7.1/embedded)
  AucUtilScanStart, v7.1.5675.5347(7.1/embedded)
  AucUtilSearchUI, v7.1.5675.5672(7.1/embedded)
  AucUtilSimpleAuction, v7.1.5675.5654(7.1/embedded)
  AucUtilVendMarkup, v7.1.5675.4828(7.1/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BeanCounter, v7.1.5675 (TasmanianThylacine)
  BlizzMove, v
  bobFastLoot, v1.05
  BrokerGarrison, v2.0.8.1
  BrokerPortals, v1.9.1
  BrokerProfessionsMenu, v7.1.0.1
  BulkOrder, vv1.18
  ButtonForge, v0.9.46
  CanIMogIt, v7.1.0.01
  Carbonite, v7.1.0
  ClassTimer, v2.3.70100.1
  Configator, v5.1.DEV.406(/embedded)
  DataStore, vr60
  DataStoreAchievements, vr43
  DataStoreAgenda, vr24
  DataStoreAuctions, vr46
  DataStoreCharacters, vr37
  DataStoreContainers, vr54
  DataStoreCrafts, vr75
  DataStoreCurrencies, vr32
  DataStoreGarrisons, vr17
  DataStoreInventory, vr47
  DataStoreMails, vr47
  DataStorePets, vr40
  DataStoreQuests, vr38
  DataStoreReputations, vr38
  DataStoreSpells, vr28
  DataStoreStats, vr27
  DataStoreTalents, vr55
  DBMCore, v
  DBMDefaultSkin, v
  DBMLDB, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.1.5675 (TasmanianThylacine)
  EnchantrixBarker, v7.1.5675 (TasmanianThylacine)
  EventAlert, v7.0.2
  GarrisonMissionManager, vv52
  GatherMate2, v1.38.1
  GSCore, v151
  GSDanaMacros, vv0.7 - Legion Beta
  GSSequenceEditor, v1.5
  GTFO, v4.41.2
  HandyNotes, vv1.4.11
  HandyNotesLegionTreasures, v1
  HandyNotesSuramarTelemancy, v1
  HealBot, v7.1.0.0
  HealBotTips, v7.1.0.0
  Informant, v7.1.5675 (TasmanianThylacine)
  InstancePortals, v8
  ISeeYouToo, v
  IskarAssist, v
  KuiNameplates, v
  KuiNameplatesCore, v
  KuiNameplatesCoreConfig, v
  LargerMacroIconSelection, vv1.1.4
  LibExtraTip, v5.12.DEV.412(/embedded)
  LibTTScan10, vv4
  LiteBag, v7.1.4
  MasterPlanA, vA
  MountFarmHelper, v7.1.0
  NPCScan, v7.1.0.1
  NugComboBar, v
  Omen, v3.1.12
  Outfitter, v5.15.6
  Ovale, v7.1.0.0
  Overachiever, v0.98
  Paste, v1.4.9
  PetTracker, v7.1.0
  PetTrackerBreeds, v
  PetTrackerConfig, v
  PetTrackerJournal, v
  PetTrackerSwitcher, v
  PetTrackerUpgrades, v
  Postal, vv3.5.8
  PremadeNotifier, v
  QuickMark, v60100
  Recount, vv7.1.0a release
  Rematch, v4.5.6
  RobBossMods, v
  SavedInstances, v7.0.6
  SimpleILevel, v3.3.9
  SimpleILevelGroup, v3.3.9
  SimpleILevelResilience, v3.3.9
  SimpleILevelSocial, v3.3.9
  SlideBar, v7.1.5675 (TasmanianThylacine)
  SpellFlashCore, v2.1.3
  SpellStealer, v1.85
  Stubby, v7.1.5675 (TasmanianThylacine)
  SushiSort, v7.0.0.0
  TheUndermineJournal, v4.7.20161101
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.9.2.70100
  TitanBag, v5.9.2.70100
  TitanClock, v5.9.2.70100
  TitanCurrency, v7.0.3a
  TitanEmote, v1.0.21.70000
  TitanGold, v5.9.2.70100
  TitanLocation, v5.9.2.70100
  TitanLootType, v5.9.2.70100
  TitanPerformance, v5.9.2.70100
  TitanRepair, v5.9.2.70100
  TitanSocial, v7.1.0
  TitanVolume, v5.9.2.70100
  TitanXP, v5.9.2.70100
  TomTom, vv70000-1.1.0
  ToyBoxEnhanced, v1.2.3
  WeakAuras, v2.2.1.9
  WorldQuestGroupFinder, v0.17.2
  WorldQuestsList, v23
  BlizRuntimeLib_enUS v7.1.0.70100 <none>
  (ck=133e)

**Comment by Thrumbar** [comment]
This is the relevent part of 
/FrameXML/WorldMapFrame.lua.

Hope it helps...

1908 function TaskPOI_OnClick(self, button)
1909	if self.worldQuest then
1910		if SpellCanTargetQuest() then
1911			if IsQuestIDValidSpellTarget(self.questID) then
1912				UseWorldMapActionButtonSpellOnQuest(self.questID);
1913				-- Assume success for responsiveness
1914				WorldMap_OnWorldQuestCompletedBySpell(self.questID);
1915			else
1916				UIErrorsFrame:AddMessage(WORLD_QUEST_CANT_COMPLETE_BY_SPELL, RED_FONT_COLOR.r, RED_FONT_COLOR.g, RED_FONT_COLOR.b);
1917			end
1918		else
1919			if ( not ChatEdit_TryInsertQuestLinkForQuestID(self.questID) ) then
1920				PlaySound("igMainMenuOptionCheckBoxOn");
1921
1922				if IsShiftKeyDown() then
1923					if IsWorldQuestHardWatched(self.questID) or (IsWorldQuestWatched(self.questID) and GetSuperTrackedQuestID() == self.questID) then
1924						BonusObjectiveTracker_UntrackWorldQuest(self.questID);
1925					else
1926						BonusObjectiveTracker_TrackWorldQuest(self.questID, true);
1927					end
1928				else
1929					if IsWorldQuestHardWatched(self.questID) then
1930						SetSuperTrackedQuestID(self.questID);
1931					else
1932						BonusObjectiveTracker_TrackWorldQuest(self.questID);
1933					end
1934				end
1935			end
1936		end
1937	end
1938end

**Comment by IrcDirk** [comment]
Need to wait till i have Silver Hand Orders to debug this...

**Comment by SteveEbey73742** [comment]
Could NPC Scan Overlay be the culprit?

**Comment by Palonblade** [comment]
Any news on this or still waiting to unlock Silver Hand Orders? Issue exists on my mage and pally now.

**Comment by IrcDirk** [comment]
Got little time to play lately. Try using workaround (doesnt know if this helps): open orginal Blizzard map with ALT+M and then using orginal emmisary icons.

**Comment by Palonblade** [comment]
I have been using the Blizzard map.

**Comment by qlesz** [comment]
Opening blizz map doesn't help because extra button does nothing with carbonite addon active. The only option is to deactivate carb do the quest and activate carb again witch is really annoying.

**Comment by IrcDirk** [comment]
Ok, sorry for inconvenience with this feature, but i dont have time for fixing this now. Ill will try fix this after christmass.

**Comment by Palonblade** [comment]
Any movement on this? I now have 4 toons that have to unload Carb to get this done without error.

**Comment by IrcDirk** [comment]
No time for playing and specialy farming those order resources. Anyone now fast way to farm15000 order resources?

**Comment by Palonblade** [comment]
World quests seem to be the fastest, you can do the ones specifically for resources and also you get a lot of resources when completing the emissary quest each day (4 quests for a faction, turn in gives resources). Also if you have not completed your order hall chain many of those give resources.

**Comment by qlesz** [comment]
There is no fast way unfortunatelly but all ways joint together make it faster. What i was doing is World quests prio resource quest + chest (but chest resources is random, you can get gold instead) + all hidden treasures and rare mobs on my way (50 - 80 average) + blood of sargreas is decent resource boost if u have loads of them (1 blood = 200 resources)

**Comment by IrcDirk** [comment]
Need to do every wquest for orders daily then... Blood of Sergreas is souldbound so no luck this time :( used all on this char for a little boost.

**Comment by IrcDirk** [comment]
Silver Hand orders next, need to colect 12,5k.

**Comment by IrcDirk** [comment]
Ok, farmed. Just need to wait 5 days till is enabled.

**Comment by IrcDirk** [comment]
Ok should be fixed. Please check and report back.

**Comment by Palonblade** [comment]
Worked on 5 classes. You Rock!!! Thanks so much for addressing this.

**Comment by Palonblade** [comment]
This issue is back with the GitHub I downloaded today.

Date: 2017-04-13 11:12:16
ID: 2
Error occured in: AddOn: Carbonite
Count: 2
Message: Error: AddOn Carbonite attempted to call a forbidden function (SpellStopTargeting()) from a tainted execution path.
Debug:
   [C]: SpellStopTargeting()
   ..\FrameXML\WorldMapActionButton.lua:61: oClear()
   Carbonite\NxMap.lua:3106: Clear()
   ..\FrameXML\WorldMapActionButton.lua:67: Refresh()
   ..\FrameXML\WorldMapActionButton.lua:19: SetMapAreaID()
   ..\FrameXML\WorldMapFrame.lua:428:
      ..\FrameXML\WorldMapFrame.lua:390
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: ?
   [C]: Hide()
   ..\FrameXML\UIParent.lua:2404: SetUIPanel()
   ..\FrameXML\UIParent.lua:2431: MoveUIPanel()
   ..\FrameXML\UIParent.lua:2462: HideUIPanel()
   ..\FrameXML\UIParent.lua:2136:
      ..\FrameXML\UIParent.lua:2128
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:2930:
      ..\FrameXML\UIParent.lua:2917
   [C]: ?
   [C]: HideUIPanel()
   ..\FrameXML\WorldMapFrame.lua:331:
      ..\FrameXML\WorldMapFrame.lua:331
Locals:
None

**Comment by IrcDirk** [comment]
Fixed. Try and report back.

**Comment by IrcDirk** [comment]
Should be fixed by other fix.

**Comment by IrcDirk** [comment]
Closing. More info in #644.
